module "load_balancer" {
  source       = "../.."
  LOAD_BALANCER_NAME = "lb-test"
  SECURITY_GROUP_NAME = "gp-lb-test"
  SECURITY_GROUP_DESCRIPTION = "Description for example"
  SECURITY_GROUP_INGRESS_BLOCK = [{SECURITY_GROUP_INGRESS_FROM_PORT = 80, SECURITY_GROUP_INGRESS_TO_PORT = 80, SECURITY_GROUP_INGRESS_RULES_PROTOCOL = "tcp", SECURITY_GROUP_INGRESS_CIDR_BLOCK = ["0.0.0.0/0"]}]
  SECURITY_GROUP_EGRESS_BLOCK = [{SECURITY_GROUP_EGRESS_FROM_PORT = 0, SECURITY_GROUP_EGRESS_TO_PORT = 0, SECURITY_GROUP_EGRESS_RULES_PROTOCOL = "-1", SECURITY_GROUP_EGRESS_CIDR_BLOCK = ["0.0.0.0/0"]}]
  LB_SUBNET_IDS = ["subnet-1-id", "subnet-2-id"]
  LOAD_BALANCER_TARGET_GROUP_NAME = "tg-gp-test"
}